export const spacing = {
  semantic: {
    'page-x': '1.5rem',
    'page-x-desktop': '2rem',
    'page-header-top': '1.5rem',
    'page-header-top-desktop': '1.5rem',
    'page-header-bottom': '1.5rem',
    'page-header-bottom-desktop': '2rem',
    'page-section-y': '1.5rem',
    'page-section-y-desktop': '2rem',
    'page-inset-y': '1rem',
    'page-inset-y-desktop': '1.5rem',
    'card-gap': '1rem',
    'card-gap-desktop': '1.5rem',
    'modal-header-x': '1.5rem',
    'modal-header-y': '1rem',
    'modal-body': '1.5rem',
    'modal-body-desktop': '1.5rem',
    'modal-footer-x': '1.5rem',
    'modal-footer-y': '1rem',
    'mobile-nav-x': '0.75rem',
    'mobile-nav-top': '0.5rem',
    'mobile-nav-bottom-extra': '0.625rem',
    'mobile-nav-popover-bottom': '5.5rem',
    'drawer-inset': '0.75rem',
    'auth-shell-desktop': '2rem',
    'auth-header-top': '3rem',
    'auth-header-top-desktop': '2rem',
    'auth-header-bottom': '1rem',
    'auth-content-y': '1.5rem',
    'auth-content-bottom-desktop': '3rem',
    'detail-top': '2.25rem',
    'detail-bottom': '6rem',
    'detail-desktop': '3rem',
    'list-item-y': '1.25rem',
  },
  brands: {
    'central-coruja': {
      'page-x-desktop': '1.5rem',
      'card-gap-desktop': '1.25rem',
      'page-inset-y-desktop': '1.25rem',
    },
  },
} as const

export type SpacingSemanticToken = keyof typeof spacing.semantic
