import { 
  Home, 
  Search, 
  Library, 
  User, 
  ChevronLeft, 
  MoreHorizontal, 
  Play, 
  Pause, 
  SkipBack, 
  SkipForward, 
  BookOpen, 
  Book,
  Headphones, 
  Video, 
  Paperclip,
  Download,
  FileText,
  Settings,
  LogOut,
  HelpCircle,
  Mail,
  Grid,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  Eye,
  EyeOff,
  X,
  Filter,
  Check,
  Plus,
  Edit,
  Trash2,
  AlertCircle,
  Upload,
  ExternalLink
} from 'lucide-react';

export const Icons = {
  Home, Search, Library, User, ChevronLeft, MoreHorizontal,
  Play, Pause, SkipBack, SkipForward, BookOpen, Book, Headphones, 
  Video, Paperclip, Download, FileText, Settings, LogOut,
  HelpCircle, Mail, Grid, Volume2, VolumeX, Maximize, Minimize,
  Eye, EyeOff, X, Filter, Check, Plus, Edit, Trash2, AlertCircle, Upload, ExternalLink
};