import {
  Home,
  Search,
  Library,
  User,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  BookOpen,
  Book,
  Headphones,
  Video,
  Paperclip,
  Download,
  FileText,
  Settings,
  LogOut,
  HelpCircle,
  Mail,
  Grid,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  Eye,
  EyeOff,
  X,
  Filter,
  Check,
  Plus,
  Edit,
  Trash2,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  Database,
  Send,
  BarChart3,
  History,
  LineChart,
  RotateCcw,
  TrendingUp,
  Upload,
  ExternalLink,
  RotateCw,
  Smartphone,
  Image,
  Palette,
  Droplets,
  ArrowUpDown,
  ArrowDown,
  ArrowUp,
  ChevronDown,
  Ticket,
  Lock,
  Users,
  Type
} from 'lucide-react';

export const Icons = {
  Home, Search, Library, User, ChevronLeft, ChevronRight, MoreHorizontal,
  Play, Pause, SkipBack, SkipForward, BookOpen, Book, Headphones,
  Video, Paperclip, Download, FileText, Settings, LogOut,
  HelpCircle, Mail, Grid, Volume2, VolumeX, Maximize, Minimize,
  Eye, EyeOff, X, Filter, Check, Plus, Edit, Trash2, AlertCircle, AlertTriangle, CheckCircle, Database, Send, BarChart3, History, LineChart, RotateCcw, TrendingUp, Upload, ExternalLink, RotateCw, Smartphone, Image, Palette, Droplets, ArrowUpDown, ArrowDown, ArrowUp, ChevronDown, Ticket, Lock, Users, Type
};